# This is a basic workflow to help you get started with Actions

name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install muwerk libraries
      run: |
        pio lib -g install ustd
        pio lib -g install muwerk
        pio lib -g install munet
        pio lib -g install mufonts
        pio lib -g install mupplet-core
        pio lib -g install Arduino_JSON
        pio lib -g install PubSubClient@2.7
        pio lib -g install Adafruit BusIO
        pio lib -g install Adafruit GFX Library
        pio lib -g install SPI
    - name: Run PlatformIO
      run:
        pio ci --lib="." --board=d1_mini examples/bigMatrixClock/bigMatrixClock.ino
